### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by jessethach** [waste-not/waste-not#56]
Need to let users know when password/username is incorrect. Also need to show users that all fields are required.

**Comment by jessethach** [comment]
- [x]  Client side form field validation
- [x]  Asynchronous validation to confirm is user already exists
- [x]  Create backend route that will check username in database
- [x]  Username/Password error alert

**Comment by xxnatc** [comment]
**Re: backend route that checks for username**
There already is a middleware on the `/signup` route to check for unique username (`signupValidation`). Response will end in `400 (Bad Request)` with a msg `'username taken'` if username already exists and nothing will be saved to database.

**Comment by jessethach** [comment]
@xxnatc Perfect, I'll use that on a route that then!
