### ISSUE TITLE
Signup number fields have +/- buttons.

### ISSUE THREAD

**Issue by arialaurel** [waste-not/waste-not#83]
The default for `number` type inputs (atleast in Chrome) is to display little up and down buttons inside the right of the input to allow easy increment/decrement. Clearly this is not appropriate for zipcodes and phone numbers.

**Comment by arialaurel** [comment]
Gist about why zipcodes and phone numbers should be type text and not number: https://gist.github.com/jeremy2/2479338

**Comment by jessethach** [comment]
We can change this pretty easily. I'll make sure to include it in the next PR.
